# Generated by Django 4.0.3 on 2022-04-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendPost',
        ),
    ]
