# Generated by Django 4.0.3 on 2022-04-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_delete_recommendpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
