# Generated by Django 4.0.3 on 2022-04-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recommend_no', models.AutoField(primary_key=True, serialize=False)),
                ('recommend_rating', models.FloatField()),
            ],
            options={
                'db_table': 'recommend',
                'managed': False,
            },
        ),
    ]
