export const CategoryData = [
  "Space Exploration",
  "Novel-based",
  "Wargame",
  "Puzzle",
  "Word Game",
  "Collectible Components",
  "Mythology",
  "Civil War",
  "Expansion for Base-game",
  "Nautical",
  "Pirates",
  "Exploration",
  "Age of Reason",
  "Negotiation",
  "Science Fiction",
  "Modern Warfare",
  "Children's Game",
  "Transportation",
  "Religious",
  "Book",
  "World War I",
  "Bluffing",
  "Real-time",
  "Travel",
  "Zombies",
  "Political",
  "Animals",
  "Print & Play",
  "Ancient",
  "Trains",
  "Abstract Strategy",
  "Trivia",
  "Miniatures",
  "none",
  "Movies / TV / Radio theme",
  "Medical",
  "Territory Building",
  "Civilization",
  "Fighting",
  "Post-Napoleonic",
  "American Revolutionary War",
  "Renaissance",
  "Dice",
  "Farming",
  "Arabian",
  "Environmental",
  "Adventure",
  "American West",
  "Industry / Manufacturing",
  "Murder/Mystery",
  "Number",
  "Action / Dexterity",
  "Fantasy",
  "Horror",
  "Aviation / Flight",
  "Educational",
  "Deduction",
  "Video Game Theme",
  "World War II",
  "Card Game",
  "Economic",
  "Sports",
  "Spies/Secret Agents",
  "American Indian Wars",
  "Prehistoric",
  "City Building",
  "Humor",
  "Memory",
  "Comic Book / Strip",
  "Maze",
  "Electronic",
  "Party Game",
  "Mature / Adult",
  "Medieval",
];
